### PR TITLE
Added v312 for 2010/ern-main/312

### PR DESCRIPTION
**Pull request by parndt**
@sshaw this _seems_ to work.. is there anything obviously bad about it?

### CODE REVIEW

**Comment by parndt** [comment]
@sshaw hey, sorry to bother you, but what do you think about these changes?

**Comment by sshaw** [comment]
Oh what what what from may 21, sorry must have missed the :octocat: alert. The diff will kill my weak cell connection but ill take a look when im back to the motherland ~6 days. Are there tests? Need tests.

**Comment by parndt** [comment]
Alas, it is lacking tests. Remind me if I still haven't done this by the time you come to review it properly.
Enjoy your weak cell connection :palm_tree:

**Comment by sshaw** [comment]
Check the contrib doc for details on test creation.

**Comment by sshaw** [comment]
Oh, now that I'm back to high speed land, I see that I didn't miss this, but I didn't merge back in May [do to lack of tests](https://github.com/sshaw/ddex/issues/7#issuecomment-104480376) :no_good:.

Other than that things seem to be okay. But please try to add them, let me know if you have any questions -I'm here to help! :muscle:

**Comment by parndt** [comment]
@sshaw yup - fair enough!

**Comment by sshaw** [comment]
Closing. We're on 4.3 now so should not be an issue :)

**Pull request closed without merging**
